sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: y1M+mW0gS9YBVxpVNYrDGctQ8qP0jQYKYCAhzZxeMi3J/dFNNmn1kFRFAO1KceOzaju8W/PR1JPp1/Lu09jdY6a1LotJk1tfPfVAs+wKOb/BhXhvFG2k/nkXwlMD1N0x6rBgJ1Bi1t6F53yp0ZV6vcNkNkMbmS/A/EXdzpEenlX+yGo87V3zO829kfaTf33/AL/Qqa3F0+lmWnZdTaG6jYiZLvf9fvCkxT39734UqjEAzoKWEGEyd7kcZJTI3EBcZfemU83YRcHINTqzsQahyS9qshv8dUsQ2Tsx2CUrUq3BT5gSDqJZ8LlZsxdXbn5ZdzLZjtQwhji/ISsdSSycift8ZdS3KLy9LjDzhygTHDGgCAybykoKUzrefMmE9RgDZSi/0qBLkRWw8K3BovVHNrA2dTYpP8cCH4argHDFdgNp65RWkuLhSEuhw+pHvOA7I5Gf1bp7sHrZn80ea/4aJOEhClS2/3IzM+OOzgK5/TN51qUW98kO1cWzbKcud954FBREXtN8MbVIqXTP5vH6re+k5t6lujAZ03pvh3CkKzw7Uh46jSznxea25ALZp+hcjm5KhrDbSzREggJllVKdnOQPPYnJyUIo53QyIfnHXAuXwFKLPD/riRueYonRgphZmw1QpIwRCcg853fRzPpMeISXJe/1A+FJWJEPmTv3uZQ=
  - secure: U+Ax9H0LawJ+h6DhEGgeu8RpLZbKE7ljEaoOP8vSI5SCvabrt/Q2Ld7dKGUw9VoYWScoER23tzVfbPuLYLTmV/SDT0hcTmozw03vRZkmc70IUi2lD/KECPPSLNfg/meLaln+6DE5+8Uk2tHbSY+9xg8KUG8xecbSL1Ih5rNN4Ro0DV/mRhYSbn4o8LbLr89iNnTOwyafFrQAxfGyDxOMRZ1snduW6u60z1SHld+yQsAXJiKNzF2tIuclPw+9068FtjPYbcepkl2Zs/ZY5S54kHiEFzePou/Y/piWl8fShVzL1WeTcSXWH4GpCzDiOO2ml9ZU957hacNf4rysGErn82Io7/bSEokY6N18LvtpyqF4gdHZMhWxB+WkRHLUg9gaBgILYbfFVYDGislFA8WQ4Ug2MFrUPXnQ8/11+7BJ51/OQLx3QuMaiO/GiRnR/AsO8LqirnUPbhS3eMjn4r/pfXOPP+L9VnJoB5BKBssYnvJ78CCU82SpPPMgi3GqhvKvL2HgPbcnMSXhX4jjQRdVuiaHcnYDouD6Qxzb3ec4WztVv7XJVK/7LgMZSl2kadVEJw5TIeSJtWgX9C9+WfYNR7C2Ewc74IJ5wRR8V806Fn+rlYUXnUAIqSucIiVOW8iSkYN/DcU3cZSQ12DqSLqJfIB9tc1sR3O+xaWC4Yd7v3Q=
