sudo: required
dist: trusty
language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
script: echo "This design module has no tests"
after_success:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET" -in deploy.enc -out deploy_key -d; fi'
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 755 ghp.sh
  - ./ghp.sh
env:
  global:
    - secure: y1M+mW0gS9YBVxpVNYrDGctQ8qP0jQYKYCAhzZxeMi3J/dFNNmn1kFRFAO1KceOzaju8W/PR1JPp1/Lu09jdY6a1LotJk1tfPfVAs+wKOb/BhXhvFG2k/nkXwlMD1N0x6rBgJ1Bi1t6F53yp0ZV6vcNkNkMbmS/A/EXdzpEenlX+yGo87V3zO829kfaTf33/AL/Qqa3F0+lmWnZdTaG6jYiZLvf9fvCkxT39734UqjEAzoKWEGEyd7kcZJTI3EBcZfemU83YRcHINTqzsQahyS9qshv8dUsQ2Tsx2CUrUq3BT5gSDqJZ8LlZsxdXbn5ZdzLZjtQwhji/ISsdSSycift8ZdS3KLy9LjDzhygTHDGgCAybykoKUzrefMmE9RgDZSi/0qBLkRWw8K3BovVHNrA2dTYpP8cCH4argHDFdgNp65RWkuLhSEuhw+pHvOA7I5Gf1bp7sHrZn80ea/4aJOEhClS2/3IzM+OOzgK5/TN51qUW98kO1cWzbKcud954FBREXtN8MbVIqXTP5vH6re+k5t6lujAZ03pvh3CkKzw7Uh46jSznxea25ALZp+hcjm5KhrDbSzREggJllVKdnOQPPYnJyUIo53QyIfnHXAuXwFKLPD/riRueYonRgphZmw1QpIwRCcg853fRzPpMeISXJe/1A+FJWJEPmTv3uZQ=
    - secure: U+Ax9H0LawJ+h6DhEGgeu8RpLZbKE7ljEaoOP8vSI5SCvabrt/Q2Ld7dKGUw9VoYWScoER23tzVfbPuLYLTmV/SDT0hcTmozw03vRZkmc70IUi2lD/KECPPSLNfg/meLaln+6DE5+8Uk2tHbSY+9xg8KUG8xecbSL1Ih5rNN4Ro0DV/mRhYSbn4o8LbLr89iNnTOwyafFrQAxfGyDxOMRZ1snduW6u60z1SHld+yQsAXJiKNzF2tIuclPw+9068FtjPYbcepkl2Zs/ZY5S54kHiEFzePou/Y/piWl8fShVzL1WeTcSXWH4GpCzDiOO2ml9ZU957hacNf4rysGErn82Io7/bSEokY6N18LvtpyqF4gdHZMhWxB+WkRHLUg9gaBgILYbfFVYDGislFA8WQ4Ug2MFrUPXnQ8/11+7BJ51/OQLx3QuMaiO/GiRnR/AsO8LqirnUPbhS3eMjn4r/pfXOPP+L9VnJoB5BKBssYnvJ78CCU82SpPPMgi3GqhvKvL2HgPbcnMSXhX4jjQRdVuiaHcnYDouD6Qxzb3ec4WztVv7XJVK/7LgMZSl2kadVEJw5TIeSJtWgX9C9+WfYNR7C2Ewc74IJ5wRR8V806Fn+rlYUXnUAIqSucIiVOW8iSkYN/DcU3cZSQ12DqSLqJfIB9tc1sR3O+xaWC4Yd7v3Q=
    - secure: Wn0T+GKjUyxac4f4yZwNjQJDigkNlnzK9Tpg15tFAngU8skJ1MQOZ9cROwZfRn9d5KW0gDL8191xabph2DxV/AHQNj/UxRkfm0FlDfARIKNmXrnLBY5yHXwl65AE/C6mJh66zMJykgnzSM5B+IEepgJrUIDA5UCj48bvLklnXflDWmZW+3fqRE5c2rmQAfh4GWlRverJfZiw3/Cs1V/UOc4Mn6ut0KI61/ANA4yssdneB0+sCyBf96ZJmV6RpJUgkRkbTS26DecUEPKRTgIG9f5Ad4aJLVXevYJMGv835A0Q+7H34ArRZLhH6vZHzCEc2u6PmQGWrtRcAia9DB7iN4l6MyhUwIrUoOIN2PR6gttJiUDrAp3LLfn/k2+kg3tvyY0K1wOGXn4RbkKx+96cKc2hs0zNlfEoVubQkLeS1zT+JMmD2/DQi5KU3hOuuVqR2gAC+lHDrN4KrTlaLJ06IRQ+QHcK5+6dMmUKZEYRUjthSjTkgzxKXXnPDsm2EFLlrMISc5Q5vshJznKN5qkjDdVVbr6siF2QEI8LK8lmhPLuBgtcky9iPZ6G6piJlfGZftcvQmd3i8VYr8KBzg8b9JM2ofzworZ7nYYAAyWBu50peEjSf+/yGbGFlLUFMhYZ+LR2WiGklcdiTgv/yEjNvSrncOL6ilRmuL77fUUntYM=
    - secure: ZPjRXYkY86IOFxE5VYUfwT1sdVRsJhkdnQvpSNgZZL/FkBfxTEYQoAaI4vylMKD+VQZuZfTBAJgQaplqXsMVSH1dBJFX9wWx3+VUrLcBKId9chOrUNXorpCCZd1y1Q1MgtatrT/OWHv/v7dpKuWFWmovBdmGyNTgegJk1rHHBw6CB7KZ5N5kylbEukeMrb6oGZZOZkkGmo7v6xE4vkxzYsx4QsfwWogEtZm05XLwXCx/fRYdDuabiD43WjCW0w3YRObw/4P+HnrqptTGkRoPI18TRB1HUbmEj0C1nYtjOBv51Tb3DVg9owP9fA3ztBW9GC4K6cBrLCIvSoTC72PRd+6A9xTvJaVyUjomEf11T/NhAfuOZB1A+Vb1FFB4j+xEyFovkCsFXqnCAkEt/gOILNSIQbeV2wV0Sq/1rZY14pQelaHGp147bu5vOOJsfYvVTGRLN82xoyv+71LzafMygoCGGSOQxNbFVhwTPGASWMaXWSAd/NIBcMoWlrX0j8dVC4S6bfYGU4z6doKlztgv9ikD17Kv2wzsxFG3opJxsbHNbFq4ZwGr0EerYc9Lc63YUIHhOFwn41vdJDD3+dNgeMWgVlmRFjwllJo27mtREW1/OEW6/K+34LvwC1ST9ivSD18r+wBRkDKQgyQXOCZ8EQQ4MAk0+OCI5VGoezeHNw4=

