sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
env:
  global:
  - secure: J+vR12LGBX320ZX9ugg/nMOsOipJjaqHnaqwwQa1x4uqAOL+paNCpTfPW5AI7atTHVevCQJ/sLboBTO20cWofgSbHRGGx46SUPNETE1R+Alk8aCZyzjg8yF5UblA7olv2iiQZlggaW+kzia1gA/HDjoIsHNJzMfD5856gQcXwfID4cUA4uTu+XWPtL9TAFmQ3bHZPYyT7XWhbW3Lf27dyEZ4zRpITJC400+thkjturAuTyDhOuGT36MivfI5nd8Mfi6eLifQj+LcDhU2aTiFYNelkyd5LJuUlDQumbDU6SxcUf9EvhFr95OANEAtXeo4z2aWtgaPD7D0ovnud/9JXDSGSE6V5Z0oHr2jMUIzzlBiKIGHkuP81BaWeQtpCncE2Pz9hYEA51EWL3ui5WlRMWyhZXKMOADIqGIvWyY0BoJJbhUROi/sSquf+mjbBzDIRYdwPi8vj4WCbT1311MMinyLXCH1jzBprSZai+t573W/RW8011d+YScGP4m5Nj/YstQMCXA1ZNGUTCvwF4bjLk6nQlesYlluRwM7u8LHuGw/ECUQ7nkBqYrOU/pg2e2Z7/8vg57eNrP026bKHWjHDfh2F8exTSOjxMFVRY+xqEhdcply5soV9DlFmebtqGbGNmpvLFztGKXtCAUwjUb3rAhs4O8lZlmM22bBVT2qyK8=
  - secure: pXjc+W6qO1yZNwp8BJ4H/tbEeaE6685Cs5xnZ6G1cL+TE0aS1RpaZfEcH2/cq8RdoSZrADyZGziOmJBxzhFNdUfi/uL15aGrdSmnAu034m/0YQnhgn+UEvnY/u/ezBpU18+fNlblSEjUj1SW/GwF1Dxtxk3In7gQJFdlZXqALAOcx5qnb3M+wpOMIOg2LDUcM3abxhQ5YOoY+C2eszYfINf2ZlzURMpQCBgx1O0SzhqqsNldtuXgE0dFDdVi3mNnI/wmgjIECOmIds5wBiipExH2fDvoT4Ruqi93xWDc+uliO8TW7bawPJ1b+FxC/loyeyPQILtQsP0ndt/HZPdHn8e6cs5B6P3nuJo8EQ1AoTOZ5Mddb2CKlqj1veMjvlwrMQqVxgCL2/vGJrpGFr0zaoo4orlClsB8XWB1RTPwchvjzYsBriC3WJF/QnJfUcFktk2fR3fODuE+V6hqStUVZwNnpeDWAgAND1gCARGP0rMa9c8tnLE9MNcP3lLZKYb9EaqG78upGN0Vi3k8/9KHmXdiZnLarYVCnj3Pi0kzAsHi+4jcOHTgKDN3HNuC4Www4qR2pYx4/0J5fd7To95CmQC4GZvOLmjHXknahSt4bd73nJIjgtrt+uMjmE80yHdrTKd8/5jaw8/Fk2UL4WAb67reUoh6cbxhwjZp+fNw3Iw=
  - secure: Ziu6s1ZKNySA3lW9dbtyRaXt0YQ+7GBXIxedydi2EwdZWBq/fmj3o+tmd93rlEsnRJ2yjdJ1TUXYfY9IPpTHX+KemmTDzFGWD2lfTotzSmgUl5A2HrpC7H4ymYR2IJe3hhXrVIBwGdB4HOmCXmgfA3CWca9PvEMIQJ6CxS7GlHzh8sPp0AibYaENssxjIOd5k52gwkK30TXLlTSCBynhyhKfvvZ9eGJQ13OrAsaqxDdnPmjZloG+jFs3aBHdPIIeXSBzrartT1VPYtwbXfMCO6r1UY6LWxlbaUZuXoRx0hBa/YMpvFtFFGEB9mmh9k/Phzr0RowV2hLA4L3y+HSTQkVlXVslPbKW1qpOQSSjIqtAktsDuokh/bk6o3/IMSxa9EmLvm12zU25gbfpzOLldZiPZDJpeVXDivMkfK8t9YdrvomVhndttULuCwpZ+E4WVaTPQm72Wuv5lMQLpGA+bj+mDr1cDhuuRZgi46+RbUPp7gHyqHXJn1zyw+p9ZYk+ltR1aTvZAeBMPdn11v/gv5mtZYh5SuPBAl8nAlOBeN00XqW6nFgBRFaWXTQNe0uhDSonh4EnoDS4A03oCEHQAZJl6khoilQIv3BE0IUUX+AEUKKqF7IFzW044k6xcnq8pZTrsgqC+W1azusQj7iUJGqoabgL6LGG9d3ZJzPz4DQ=
